#!/usr/bin/env python3
"""Merge N fndsa_precompute_profile_run_*.json into one headline file via the
per-field MEAN (not median): with a small run count the median just picks one
run's raw value and discards the rest, which is not a defensible estimator and
reads as cherry-picking. Mean uses every observation.

Emitted by pkg/fndsa/precompute_profile_test.go (EMIT_PROFILE=1). Feeds
scripts/generate_article_graphics.py -> fig_18 (resident expanded-key material)
via persistent_bytes_per_key, and documents the precompute time-memory tradeoff.

Usage:
    python3 scripts/aggregate_precompute_profile.py \
        --glob 'backend/benchmark-results/runs/fndsa_precompute_profile_run_*.json' \
        --out backend/benchmark-results/fndsa_precompute_profile.json
"""

from __future__ import annotations

import argparse
import glob
import json
import statistics
from pathlib import Path


def mean(values: list[float]) -> float:
    return statistics.fmean(values)


def sample_stdev(values: list[float]) -> float:
    return statistics.stdev(values) if len(values) > 1 else 0.0


def aggregate(pattern: str, out_path: str) -> None:
    paths = sorted(glob.glob(pattern))
    if not paths:
        raise FileNotFoundError(f"No files matched: {pattern}")
    runs = [json.loads(Path(p).read_text(encoding="utf-8")) for p in paths]
    print(f"precompute-profile: merging {len(runs)} run(s):")
    for p in paths:
        print(f"  - {p}")

    first = runs[0]
    break_even = [r["break_even_signatures"] for r in runs]
    # Every run holds 1/10/100 signers; average the RSS delta per bucket.
    signer_counts = first["rss_delta_kb_by_signers"].keys()
    rss_mean = {
        k: mean([r["rss_delta_kb_by_signers"][k] for r in runs]) for k in signer_counts
    }

    merged = {
        "_note": (
            f"Headline = mean of {len(runs)} independent run(s). persistent_bytes_per_key is "
            "deterministic (struct + slice sizes), identical on any host. Timing/RSS fields are "
            "host-specific — run on the target VPS for thesis figures. Per-run raw data: "
            "fndsa_precompute_profile_run_*.json. Generated by scripts/aggregate_precompute_profile.py."
        ),
        "aggregation": f"mean of {len(runs)} runs",
        "runs": len(runs),
        "host": first["host"],
        "degree": first["degree"],
        "build_reps": first["build_reps"],
        "sign_reps": first["sign_reps"],
        "build_mean_ms": mean([r["build_median_ms"] for r in runs]),
        "sign_dynamic_mean_ms": mean([r["sign_dynamic_median_ms"] for r in runs]),
        "sign_precomputed_mean_ms": mean([r["sign_precomputed_median_ms"] for r in runs]),
        "saving_per_signature_mean_ms": mean([r["saving_per_signature_ms"] for r in runs]),
        "break_even_signatures_mean": mean(break_even),
        "break_even_signatures_stdev": sample_stdev(break_even),
        "break_even_signatures_range": [min(break_even), max(break_even)],
        "persistent_bytes_per_key": first["persistent_bytes_per_key"],
        "rss_delta_kb_by_signers_mean": rss_mean,
        "rss_kb_per_signer_at_100": rss_mean["100"] / 100,
    }
    Path(out_path).write_text(json.dumps(merged, indent=2) + "\n", encoding="utf-8")
    print(f"precompute-profile: wrote {out_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--glob", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    aggregate(args.glob, args.out)


if __name__ == "__main__":
    main()
